Algoritmo "ConteAte10"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/3/2020
Var
// Seção de Declarações das variáveis 
   cont: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   cont <- 1
   Repita
   Escreval (cont)
   cont <- cont+1
   Ate (cont >10)
   Escreval ("Terminei de contar!")
Fimalgoritmo