Algoritmo "Combinacoes"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 1/4/2020
Var
// Seção de Declarações das variáveis 

   C1, C2: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    Para c1 := 1 ate 3 faca
         Para c2 := 1 ate 3 faca
           Escreval (C1, C2)
         FimPara
    FimPara

Fimalgoritmo