Algoritmo "ConteAte10"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/3/2020
Var
// Seção de Declarações das variáveis 
   C: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Para C <- 1 ate 10 faca
        Escreval (C)
   FimPara
   Escreval ("Terminei de contar!")
Fimalgoritmo