Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/3/2020
Var
// Seção de Declarações das variáveis 
   reais, dolares: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
        Escreva ("Quantos reais eu tenho? R$")
        Leia (reais)
        dolares <- reais/2.22
        Escreva ("Posso ter US$", dolares)

Fimalgoritmo