Algoritmo "FazSomaProcedimento"

Var

X, Y: inteiro
Procedimento soma (A,B :inteiro)
inicio
   Escreval ("Recebi o valor: ", A)
   Escreval ("Recebi o valor: ", B)
   Escreval ("A soma entre os dois é: ", A+B)
Fimprocedimento

Inicio
X <- 5
Y <- 3
Soma (X, Y)
 //A  e B sao tratadas como variaveis mas como sao passaddos como procedimento
 // sao: parametros!!
 // nem todas as linguagens aceitam o nome da variavel igual ao do parametro
Fimalgoritmo