Algoritmo "Fibonacci"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 1/4/2020
Var
   // Seção de Declarações das variáveis
   C0, C1, C2, c3, F: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   c1 <- 1
    Escreva (c0, c1)
   Para F <-1 ate 13 faca

      c2 <- c0+c1
      Escreva (c2)
      c0<- c1
      c1 <- c2
   Fimpara





Fimalgoritmo