Algoritmo "SomaParametroReferencia"

Var
 X, Y: inteiro
 Procedimento Soma (var A, B: inteiro)
 Inicio
 A <- A+1
 B <- B+2
   Escreval ("Valor de A = ", A)
   Escreval ("Valor de B = ", B)
   Escreval ("Soma A+B = ",A+B)
 FimProcedimento
Inicio
 X <- 4
 Y <- 8
 Soma (X,Y)
 Escreval ("O valor de X é: ", X)
 Escreval ("O valor de Y é: ", Y)
 // add e tirar a palavra var para entender passagem de parametro
Fimalgoritmo